### ISSUE TITLE
How to use multi touch boards as midi devices on one PC in touchdesigner?

### ISSUE THREAD

**Issue by szewingleung** [BareConductive/generic-usb-midi-interface#2] opened 2019-07-30 14:07 UTC
I have connected two touch board and it can sense two boards in touchdesigner, but there is only one board can give messages out in the MIDI Mapper and it sending double data by only one touch, what can I do to have the messages of both 2 boards?

Hope for your reply, thanks very much.

![image](https://user-images.githubusercontent.com/53482553/62136313-6e23c080-b316-11e9-9c82-b8839efe9ea8.png)

**Comment by stefandz** [comment] 2019-08-15 11:57
Duplicate of #1

**Closed as completed** 2019-08-15 11:58 UTC
